// Drives api/generate-scenes.js across an entire outline: each chapter's scene_count is split
// into calls of at most MAX_SCENES_PER_CALL scenes, the narration handed continuity via
// previousTail so the voiceover reads as one continuous script rather than disjointed fragments.

const MAX_SCENES_PER_CALL = 16;
const RETRY_BACKOFF_MS = 3000;

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function callGenerateScenes(payload) {
  const res = await fetch('/api/generate-scenes', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload),
  });
  const data = await res.json();
  if (!res.ok) throw new Error(data.error || 'Scene generation failed');
  if (!Array.isArray(data.scenes) || !data.scenes.length) throw new Error('Scene generation returned no scenes');
  return data.scenes;
}

// One retry with a fixed backoff — a second failure propagates to the caller, which by then has
// already been handed every scene generated by prior successful chunks via onProgress.
async function callWithRetry(payload) {
  try {
    return await callGenerateScenes(payload);
  } catch {
    await sleep(RETRY_BACKOFF_MS);
    return await callGenerateScenes(payload);
  }
}

// A chapter with more scenes than the per-call cap becomes several chunks, the last one taking
// whatever remains rather than every chunk being forced to an equal size.
function splitIntoChunkSizes(sceneCount) {
  const sizes = [];
  let remaining = sceneCount;
  while (remaining > 0) {
    const size = Math.min(MAX_SCENES_PER_CALL, remaining);
    sizes.push(size);
    remaining -= size;
  }
  return sizes;
}

/**
 * outline: [{ id, title, summary, scene_count }]
 * context: { topic, title, language, style, format, characterBible, references }
 * onProgress(scenesSoFar, totalScenes): called after every successful chunk with the full
 * accumulated scenes array so far — safe for the caller to both derive a progress count from
 * (scenesSoFar.length) and persist as partial, resumable state.
 */
export async function generateAllScenes(outline, context, onProgress) {
  const chapters = Array.isArray(outline) ? outline : [];
  const totalScenes = chapters.reduce((a, c) => a + (Number(c.scene_count) || 0), 0);

  // Flatten (chapter, chunk size) into one ordered job list so "first chunk of the whole video"
  // and "last chunk of the whole video" can be determined without nested-loop bookkeeping.
  const jobs = [];
  chapters.forEach((chapter) => {
    splitIntoChunkSizes(Number(chapter.scene_count) || 0).forEach((size) => jobs.push({ chapter, size }));
  });

  const allScenes = [];
  let previousTail = null;

  for (let i = 0; i < jobs.length; i++) {
    const { chapter, size } = jobs[i];
    const scenes = await callWithRetry({
      topic: context.topic,
      title: context.title,
      chapterTitle: chapter.title,
      chapterSummary: chapter.summary,
      sceneCount: size,
      language: context.language,
      style: context.style,
      format: context.format,
      characterBible: context.characterBible,
      references: context.references,
      previousTail,
      isVeryFirstChunk: i === 0,
      isVeryLastChunk: i === jobs.length - 1,
    });

    allScenes.push(...scenes);
    previousTail = scenes[scenes.length - 1]?.narration || previousTail;

    if (onProgress) onProgress(allScenes.slice(), totalScenes || allScenes.length);
  }

  return allScenes;
}
