// Drives api/generate-scenes.js across an entire outline: each chapter's scene_count is split
// into calls of at most MAX_SCENES_PER_CALL scenes, the narration handed continuity via
// previousTail so the voiceover reads as one continuous script rather than disjointed fragments.

import { isCreditExhaustedMessage } from './providerErrors';
import { postJSON } from './httpJson';

const MAX_SCENES_PER_CALL = 16;
const RETRY_BACKOFF_MS = 3000;
// Shared cap for every paid-provider concurrency pool below (images via nanobanana/gptimage,
// audio via MiniMax) — free/local engines (Pollinations, Kokoro) stay serial and untouched.
export const MAX_PAID_CONCURRENCY = 6;

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

// One retry with a fixed backoff, shared by scene generation and image generation below — a
// second failure propagates to the caller (for scenes, that's after every prior successful chunk
// has already been handed over via onProgress, so no completed work is lost). A recognized
// "credit exhausted" failure is never retried: topping up an account is not something a 3s wait
// fixes, and each pointless retry is another billable request that also 402s.
async function withRetry(fn) {
  try {
    return await fn();
  } catch (err) {
    // A caller-imposed timeout/abort (see src/lib/asyncTimeout.js) is final — retrying just reuses
    // the already-aborted signal and burns the backoff for nothing. Credit exhaustion likewise.
    if (isCreditExhaustedMessage(err?.message) || err?.name === 'AbortError' || err?.name === 'TimeoutError') throw err;
    await sleep(RETRY_BACKOFF_MS);
    return await fn();
  }
}

async function callGenerateScenes(payload) {
  const res = await fetch('/api/generate-scenes', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload),
  });
  const data = await res.json();
  if (!res.ok) throw new Error(data.error || 'Scene generation failed');
  if (!Array.isArray(data.scenes) || !data.scenes.length) throw new Error('Scene generation returned no scenes');
  // promised_follow_up only ever appears on the isVeryLastChunk request/response (see
  // api/generate-scenes.js's promisedFollowUpField) — undefined on every other chunk.
  return { scenes: data.scenes, promisedFollowUp: data.promised_follow_up || null };
}

// A chapter with more scenes than the per-call cap becomes several chunks, the last one taking
// whatever remains rather than every chunk being forced to an equal size.
function splitIntoChunkSizes(sceneCount) {
  const sizes = [];
  let remaining = sceneCount;
  while (remaining > 0) {
    const size = Math.min(MAX_SCENES_PER_CALL, remaining);
    sizes.push(size);
    remaining -= size;
  }
  return sizes;
}

/**
 * outline: [{ id, title, summary, scene_count }]
 * context: { topic, title, language, style, format, imageProvider, contentType, characterBible, references, creativeOverride, channelIntroEnabled, niche }
 * onProgress(scenesSoFar, totalScenes): called after every successful chunk with the scenes
 * generated by THIS call so far (not counting anything from a previous, already-persisted call —
 * see resumeFrom below) — safe for the caller to both derive a progress count from and persist as
 * partial, resumable state.
 * resumeFrom: { alreadyGeneratedCount, previousTail } — set when continuing a video whose scene
 * generation was interrupted partway (see fullPipelineRecipe.js/staticBackgroundRecipe.js's resume
 * check). Skips whichever whole (chapter, chunk) jobs are already accounted for by
 * alreadyGeneratedCount, and seeds narrative continuity from previousTail (the last already-written
 * scene's narration) instead of starting cold. Jobs only ever complete as a whole — onProgress
 * fires once per successful chunk, and that's the only time a partial scenes array is ever
 * persisted — so alreadyGeneratedCount always lands exactly on a job boundary, never mid-chunk.
 * Omit (or pass null) for a fresh video; this is the default, existing behavior.
 * Returns { scenes, promisedFollowUp } — scenes are ONLY the newly-generated ones from this call
 * (the caller prepends whatever it already had, see the recipes' own resume-aware scenes phase).
 * promisedFollowUp is whatever the very last chunk declared (see api/generate-scenes.js's
 * promised_follow_up field), or null when the closing CTA was generic, or this call didn't reach
 * the last chunk (resuming mid-video and something failed again before the end).
 */
export async function generateAllScenes(outline, context, onProgress, resumeFrom = null) {
  const chapters = Array.isArray(outline) ? outline : [];
  const totalScenes = chapters.reduce((a, c) => a + (Number(c.scene_count) || 0), 0);

  // Flatten (chapter, chunk size) into one ordered job list so "first chunk of the whole video"
  // and "last chunk of the whole video" can be determined without nested-loop bookkeeping.
  const jobs = [];
  chapters.forEach((chapter) => {
    splitIntoChunkSizes(Number(chapter.scene_count) || 0).forEach((size) => jobs.push({ chapter, size }));
  });

  let startJobIndex = 0;
  if (resumeFrom?.alreadyGeneratedCount) {
    let cumulative = 0;
    for (let i = 0; i < jobs.length; i++) {
      cumulative += jobs[i].size;
      if (cumulative <= resumeFrom.alreadyGeneratedCount) startJobIndex = i + 1;
      else break;
    }
  }

  const allScenes = [];
  let previousTail = resumeFrom?.previousTail || null;
  let promisedFollowUp = null;

  for (let i = startJobIndex; i < jobs.length; i++) {
    const { chapter, size } = jobs[i];
    const { scenes, promisedFollowUp: chunkPromise } = await withRetry(() => callGenerateScenes({
      topic: context.topic,
      title: context.title,
      chapterTitle: chapter.title,
      chapterSummary: chapter.summary,
      sceneCount: size,
      language: context.language,
      style: context.style,
      format: context.format,
      imageProvider: context.imageProvider,
      contentType: context.contentType,
      characterBible: context.characterBible,
      references: context.references,
      creativeOverride: context.creativeOverride,
      channelIntroEnabled: context.channelIntroEnabled,
      niche: context.niche,
      previousTail,
      isVeryFirstChunk: i === 0,
      isVeryLastChunk: i === jobs.length - 1,
    }));

    allScenes.push(...scenes);
    previousTail = scenes[scenes.length - 1]?.narration || previousTail;
    if (chunkPromise) promisedFollowUp = chunkPromise;

    if (onProgress) onProgress(allScenes.slice(), totalScenes || allScenes.length);
  }

  return { scenes: allScenes, promisedFollowUp };
}

// ---- "Paste your own script" mode (CreateStep.jsx) ----
//
// Two-call counterpart to generateAllScenes above, for a video whose narration the user wrote
// themselves rather than one Claude invents from a topic. Split into two client-visible steps
// (rather than one, like generateAllScenes) because the two calls have genuinely different
// contracts: splitScriptIntoScenes is a single call over the WHOLE script (it can't be chunked —
// scene boundaries can only be decided by reading the entire thing at once), while
// generateBeatsForScript is chunked exactly like generateAllScenes's own per-chapter loop, since
// each beats-writing call is independent per scene and there's no reason to pay for one giant call.

function whitespaceInsensitive(s) {
  return (s || '').replace(/\s+/g, '');
}

async function callSplitScriptPlan(payload) {
  const res = await fetch('/api/generate-scenes', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ mode: 'split-script', stage: 'plan', ...payload }),
  });
  const data = await res.json();
  if (!res.ok) throw new Error(data.error || 'Script splitting failed');
  if (!Array.isArray(data.scenes) || !data.scenes.length) throw new Error('Script splitting returned no scenes');
  return data;
}

/**
 * script: the user's complete, verbatim narration text.
 * context: { language, style, imageProvider, contentType, characterHints, generalNotes, references,
 * channelCharacters, thumbnailCreativeDirection } — references are the { id, label } stubs
 * (channelCharacterReferenceStubs / manual uploads), same shape TitleSelectStep.jsx sends.
 *
 * Calls api/generate-scenes.js's split-script 'plan' stage, then — never trusting the instruction
 * alone (api/generate-scenes.js's SPLIT_SCRIPT_VERBATIM_INSTRUCTION) — verifies in code that every
 * returned scene, concatenated in order and compared whitespace-insensitively, reconstructs the
 * original script exactly. Throws a clear, actionable error instead of silently handing back a
 * script the model altered.
 *
 * Returns { title, description, tags, thumbnails, characterBible (raw, NOT yet merged with the
 * channel's recurring characters — the caller does that, same as it already does for the outline
 * flow), scenes: [string, ...] } — scenes are narration-only at this point, image_beats come from
 * generateBeatsForScript below.
 */
export async function splitScriptIntoScenes(script, context) {
  const plan = await withRetry(() =>
    callSplitScriptPlan({
      script,
      language: context.language,
      style: context.style,
      imageProvider: context.imageProvider,
      contentType: context.contentType,
      characterHints: context.characterHints,
      generalNotes: context.generalNotes,
      references: context.references,
      channelCharacters: context.channelCharacters,
      thumbnailCreativeDirection: context.thumbnailCreativeDirection,
    })
  );

  if (whitespaceInsensitive(plan.scenes.join('')) !== whitespaceInsensitive(script)) {
    throw new Error(
      "The AI's scene split didn't exactly reproduce your original script word for word — nothing was generated, so your script is untouched. Please try again."
    );
  }

  return {
    title: plan.title || '',
    description: plan.description || '',
    tags: plan.tags || [],
    thumbnails: plan.thumbnail_concepts || [],
    characterBible: plan.character_bible || [],
    scenes: plan.scenes,
  };
}

async function callSplitScriptBeats(payload) {
  const res = await fetch('/api/generate-scenes', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ mode: 'split-script', stage: 'beats', ...payload }),
  });
  const data = await res.json();
  if (!res.ok) throw new Error(data.error || 'Image beat generation failed');
  if (!Array.isArray(data.scenes) || data.scenes.length !== payload.scenes.length) throw new Error('Image beat generation returned the wrong number of scenes');
  return data.scenes;
}

/**
 * narrations: the FULL, already-verified array of scene narration strings (splitScriptIntoScenes's
 * output) — never re-sent to the model for rewriting, only chunked here and handed back exactly as
 * given, paired with the image_beats each chunk's call returns.
 * characterBible/references: the MERGED versions (after mergeChannelCharacters — see App.jsx's
 * handleScriptSubmit), same as generateAllScenes's context.characterBible/references.
 * context: { style, imageProvider, format }
 * onProgress(scenesSoFar, totalScenes): same contract as generateAllScenes's own — called after
 * every successful chunk with the FULL { narration, image_beats } array built so far.
 * isStaticBackground: no per-scene images for this content type — skips the network call entirely
 * and returns each scene as { narration } only, same shape buildScenesFromRaw (App.jsx) already
 * expects for static_background.
 * Returns [{ narration, image_beats }, ...], full length, in order.
 */
export async function generateBeatsForScript(narrations, characterBible, references, context, onProgress, isStaticBackground = false) {
  const totalScenes = narrations.length;
  const allScenes = [];

  for (let i = 0; i < narrations.length; i += MAX_SCENES_PER_CALL) {
    const chunk = narrations.slice(i, i + MAX_SCENES_PER_CALL);
    if (isStaticBackground) {
      allScenes.push(...chunk.map((narration) => ({ narration })));
    } else {
      // eslint-disable-next-line no-await-in-loop
      const beatsChunk = await withRetry(() =>
        callSplitScriptBeats({
          scenes: chunk,
          style: context.style,
          imageProvider: context.imageProvider,
          format: context.format,
          characterBible,
          references,
        })
      );
      chunk.forEach((narration, idx) => {
        allScenes.push({ narration, image_beats: beatsChunk[idx]?.image_beats || [] });
      });
    }
    if (onProgress) onProgress(allScenes.slice(), totalScenes);
  }

  return allScenes;
}

async function callGenerateImage(payload, signal) {
  // postJSON (src/lib/httpJson.js) reads the body as text before parsing — a platform-level failure
  // (a maxDuration timeout, a billing/DEPLOYMENT_DISABLED block, an edge error page) returns plain
  // text or HTML with an HTTP status that still looks ordinary, and a bare res.json() on that used
  // to surface here as a bare, unreadable "Unexpected token" SyntaxError instead of an actionable
  // message — exactly what happened for thumbnail generation on 2026-09-16 (the whole deployment
  // was disabled for payment; this call is what a thumbnail regeneration goes through).
  const { ok, data } = await postJSON('/api/generate-image', payload, { signal });
  // Prefer the provider's own detail over our generic wrapper so the real cause (fal.ai's raw
  // message, or the recognized "credit exhausted" line the endpoint puts in both fields) reaches
  // the caller — and from there scene.audioError / beat.errorMessage — instead of being flattened
  // to "generation failed (HTTP 502)".
  if (!ok) throw new Error(data.detail || data.error || 'Image generation failed');
  if (!data.imageUrl) throw new Error('Image generation returned no image URL');
  return data;
}

/**
 * prompt: final, provider-appropriate prompt string (see promptBuilders.js)
 * provider: 'pollinations' | 'nanobanana' | 'gptimage'
 * referenceImages: array of data-URI or plain-URL strings, optional
 * opts: { width, height, seed, quality }
 * signal: optional AbortSignal, forwarded to fetch — omitted by every existing caller (unaffected),
 * used by mediaGenerationEngine.js's timeout wrapper to actually cancel a hung request rather than
 * just giving up on waiting for it.
 * Returns { imageUrl, provider, costUsd }. Same one-retry-with-backoff resilience as scene calls.
 */
export async function generateImage(prompt, provider, referenceImages, opts = {}, signal) {
  const payload = { provider, prompt, referenceImages: referenceImages || [], ...opts };
  return withRetry(() => callGenerateImage(payload, signal));
}

async function callGenerateAudio(payload, signal) {
  // See callGenerateImage above — same postJSON, same reason.
  const { ok, data } = await postJSON('/api/generate-audio', payload, { signal });
  // Same as callGenerateImage above: prefer data.detail (fal.ai's real message, or the recognized
  // "credit exhausted" line) so the true cause reaches scene.audioError instead of being lost.
  if (!ok) throw new Error(data.detail || data.error || 'Audio generation failed');
  if (!data.audioUrl) throw new Error('Audio generation returned no audio URL');
  return data;
}

/**
 * text: narration to synthesize
 * voice: MiniMax voice_id
 * opts: { language }
 * signal: optional AbortSignal, forwarded to fetch — same purpose as generateImage's above.
 * Returns { audioUrl, costUsd }. Same one-retry-with-backoff resilience as scene/image calls.
 */
export async function generateAudio(text, voice, opts = {}, signal) {
  const payload = { text, voice, ...opts };
  return withRetry(() => callGenerateAudio(payload, signal));
}

/**
 * Minimal concurrency-limited task runner for paid providers — no external dependency, just a
 * slot-releasing queue: each of `concurrency` parallel loops pulls the next available item as
 * soon as its previous one settles. Free/local engines (Pollinations, Kokoro) never use this —
 * they stay strictly serial by simply not calling it.
 */
export async function runWithConcurrency(items, concurrency, worker) {
  let cursor = 0;
  async function runNext() {
    while (cursor < items.length) {
      const index = cursor++;
      await worker(items[index], index);
    }
  }
  const workerCount = Math.max(1, Math.min(concurrency, items.length));
  await Promise.all(Array.from({ length: workerCount }, runNext));
}
